# Generated by Django 4.1.5 on 2023-01-26 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('datetimemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.datetimemixin')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('accounts.datetimemixin',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('datetimemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.datetimemixin')),
                ('name', models.CharField(max_length=250)),
            ],
            bases=('accounts.datetimemixin',),
        ),
    ]
