# Generated by Django 4.1.5 on 2023-01-26 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('profile', '0002_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('datetimemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.datetimemixin')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            bases=('accounts.datetimemixin',),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('datetimemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.datetimemixin')),
                ('info', models.TextField(blank=True)),
            ],
            bases=('accounts.datetimemixin',),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('datetimemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.datetimemixin')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('experience', models.IntegerField(blank=True)),
                ('description', models.ManyToManyField(to='profile.description', verbose_name='descriptions')),
            ],
            bases=('accounts.datetimemixin',),
        ),
        migrations.AddField(
            model_name='candidate',
            name='projects',
            field=models.ManyToManyField(to='profile.project'),
        ),
    ]
