# Generated by Django 4.1.5 on 2023-01-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_company_description_candidate_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
