# Generated by Django 4.1.5 on 2023-01-27 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_alter_candidate_hobbies_alter_candidate_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.company'),
        ),
    ]
