# Generated by Django 4.1.5 on 2023-01-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_project_company_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='description_key',
            field=models.ManyToManyField(blank=True, to='profile.description'),
        ),
    ]
