# Generated by Django 4.1.5 on 2023-01-27 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userrole_access_team'),
        ('profile', '0007_remove_project_description_project_description_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTitle',
            fields=[
                ('datetimemixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.datetimemixin')),
                ('skill_title', models.CharField(blank=True, max_length=250, null=True)),
                ('skill_description', models.ManyToManyField(blank=True, to='profile.skilldescription')),
            ],
            bases=('accounts.datetimemixin',),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skill_title',
            field=models.ManyToManyField(blank=True, to='profile.skilltitle'),
        ),
    ]
