# Generated by Django 4.1.5 on 2023-01-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_alter_candidate_hobbies_alter_candidate_projects'),
        ('accounts', '0002_userrole_access_accept_userrole_access_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='access_team',
            field=models.ManyToManyField(blank=True, to='profile.team'),
        ),
    ]
