# Generated by Django 4.1.5 on 2023-02-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userrole_access_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
